// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjorkrhakmhdeybfxwlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb3Jrcmhha21oZGV5YmZ4d2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODk4NjUsImV4cCI6MjA3MTM2NTg2NX0.KKCe4Sgi09pWjQr8Zs9EYJZ6B5JZ8qhWa5tDU14cnI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});